FROM ifraixedes/ubuntu/base:19.04

ARG USER_NAME

RUN mkdir /tmp/box-setup
ADD setup-scripts /tmp/box-setup/setup-scripts

RUN cd /tmp/box-setup/setup-scripts \
      && ./99-java-openjdk.sh \
      && ./99-android-tools-sdk.sh "${USER_NAME}" \
      && ./99-flutter-sdk-home.sh "${USER_NAME}" \
      && apt-get autoremove \
      && apt-get clean

RUN rm -rf /tmp/box-setup
WORKDIR "/home/${USER_NAME}"

CMD ["bash"]
